name: Lint Dockerfile

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning
