name: Deploy future tag

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Build and publish future tag
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Checkout publish workflow
        uses: Bhacaz/checkout-files@v2
        with:
          files: .github/workflows/publish/action.yml

      - name: Checkout repository code
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Build and push future image (w/ aws cli)
        uses: ./.github/workflows/publish
        with:
          bake_target: aws
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_release: false
          bake_set: |
            aws.tags=ghcr.io/stabl-energy/spacelift-runner-cdktf:future
