name: Deploy tagged

on:
  push:
    tags:
      - v*

jobs:
  deployment:
    name: Build and publish the newly tagged image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Get latest tag
        uses: oprypin/find-latest-tag@v1
        id: latest-tag
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository code
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Build and push latest image (w/ aws cli)
        uses: ./.github/workflows/publish
        with:
          bake_target: aws
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_tag: ${{ steps.latest-tag.outputs.tag }}
          publish_release: true
          release_title: ${{ steps.latest-tag.outputs.tag }}
          bake_set: |
            aws.tags=ghcr.io/stabl-energy/spacelift-runner-cdktf:latest
            aws.tags=ghcr.io/stabl-energy/spacelift-runner-cdktf:${{ steps.latest-tag.outputs.tag }}

      - name: Build and push latest image (w/ gcloud cli)
        uses: ./.github/workflows/publish
        with:
          bake_target: gcp
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_tag: ${{ steps.latest-tag.outputs.tag }}
          publish_release: false
          bake_set: |
            gcp.tags=ghcr.io/stabl-energy/spacelift-runner-cdktf:gcp-latest
            gcp.tags=ghcr.io/stabl-energy/spacelift-runner-cdktf:gcp-${{ steps.latest-tag.outputs.tag }}

      - name: Build and push latest image (w/ az cli)
        uses: ./.github/workflows/publish
        with:
          bake_target: azure
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_tag: ${{ steps.latest-tag.outputs.tag }}
          publish_release: false
          bake_set: |
            azure.tags=ghcr.io/stabl-energy/spacelift-runner-cdktf:azure-latest
            azure.tags=ghcr.io/stabl-energy/spacelift-runner-cdktf:azure-${{ steps.latest-tag.outputs.tag }}
