name: Scheduled publish

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  deployment:
    name: Rebuild and publish the latest tagged image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Get latest tag
        uses: oprypin/find-latest-tag@v1
        id: latest-tag
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository code
        uses: actions/checkout@main
        with:
          ref: ${{ steps.latest-tag.outputs.tag }}
          fetch-depth: 0

      - name: Set current date as env variable
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Set nicely formatted current date as env variable
        run: echo "TODAY_FORMATTED=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create weekly tag
        id: tag
        env:
          TAG: ${{ steps.latest-tag.outputs.tag }}_${{ env.TODAY }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if ! git rev-parse $TAG >/dev/null 2>&1; then
            git tag -a $TAG -m "Weekly rebuild of ${{ steps.latest-tag.outputs.tag }}"
            git push origin $TAG
          fi
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push weekly image (w/ aws cli)
        uses: ./.github/workflows/publish
        with:
          bake_target: aws
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_tag: ${{ steps.tag.outputs.TAG }}
          publish_release: true
          release_title: ${{ steps.latest-tag.outputs.tag }} - weekly release (${{ env.TODAY_FORMATTED }})
          release_body: |
            ## Weekly rebuild
            This is a weekly rebuild of the latest image (`${{ steps.latest-tag.outputs.tag }}`).
            The image is rebuilt to ensure that it is up to date with the latest security patches.
            ## Updated images
            ### Image with aws cli
            - `ghcr.io/stabl-energy/spacelift-runner-cdktf:latest`
            - `ghcr.io/stabl-energy/spacelift-runner-cdktf:${{ steps.tag.outputs.TAG }}`
          bake_set: |
            aws.tags=ghcr.io/stabl-energy/spacelift-runner-cdktf:latest
            aws.tags=ghcr.io/stabl-energy/spacelift-runner-cdktf:${{ steps.tag.outputs.TAG }}
